# Generated by Django 3.1.3 on 2020-12-01 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', django_mysql.models.ListCharField(models.CharField(max_length=1), max_length=18, size=9)),
                ('status', models.CharField(choices=[('A', 'active'), ('O', 'over'), ('I', 'inactive'), ('T', 'tie')], max_length=1)),
                ('current_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='game_current_player', to=settings.AUTH_USER_MODEL)),
                ('player_o', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='game_player_o', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='game_player_x', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
