version: '3'

services:
  db:
    image: mariadb:latest
    ports:
      - '33060:3306'
    environment:
       MYSQL_DATABASE: 'ttt'
       MYSQL_USER: 'leigh'
       MYSQL_PASSWORD: 'password1'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/tic_tac_toe
    ports:
      - "8000:8000"
    depends_on:
      - db
